---
title: "class_2"
output: html_document
date: "2023-02-23"
---

```{r, message=FALSE}

#let's install our libraries
#install.packages('ISLR2')

#load libraries
library('ISLR2')
library('ggplot2')

#save dataset
df <- Boston
```

Let's look at correlations before modelling
```{r}
#plot correlation
ggplot(data=df, aes(x=rm, y=nox)) +
  geom_point() +
  geom_smooth(method=lm)

#check correlation value
cor(df$rm, df$nox)

#check the significance of correlation
cor.test(df$rm, df$nox)
```


Multiple Linear Regression

```{r}
#make a model
lm_mul <- lm(medv ~ rm + nox + age, data=df)

#let's review the summary
summary(lm_mul)

#predict response (on basis of multiple predictors)
predict(lm_mul, data.frame(rm=4, nox=-.2, age=.50), interval = 'prediction')

```

Qualitative Predictor Variables

```{r}
#check the class of the 'qualitative' variable
class(df$chas)

#make sure it's a factor!
df$chas <- as.factor(df$chas)

#check the levels
contrasts(df$chas)

#change levels if required
#df$chas <- relevel(df$chas, ref=2)

#run our model
lm_qual <- lm(medv ~ chas + crim, data=df)

#review the summary
summary(lm_qual)

```

Interaction

```{r}
#interaction is multiplicative
lm_int <-lm(medv ~ lstat*age, data=df)

#review summary - hierarchical principle!
summary(lm_int)
```

